services:

#* API Web
#API 1
  api1:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: api1
    restart: always
    command:
      - bash
      - -c
      - |
        npm install --include=dev
        npm run ${API_MODE}
    volumes: # keep package.json updated
      - .:/app
    tty: true
    env_file:
      - .env
    environment:
      - PORT=${PORT_API1}
    # attach: false
    # logging:
    #   driver: "none"
    networks:
      bridge2mongo:
      brid2nginx:

#API 2
  api2:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: api2
    restart: always
    command:
      - bash
      - -c
      - |
        npm install --include=dev
        npm run ${API_MODE}
    volumes: # keep package.json updated
      - .:/app
    tty: true
    env_file:
      - .env
    environment:
      - PORT=${PORT_API2}
    # attach: false
    # logging:
    #   driver: "none"
    networks:
      bridge2mongo:
      brid2nginx:

#API 3
  api3:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: api3
    restart: always
    command:
      - bash
      - -c
      - |
        npm install --include=dev
        npm run ${API_MODE}
    volumes: # keep package.json updated
      - .:/app
    tty: true
    env_file:
      - .env
    environment:
      - PORT=${PORT_API3}
    # attach: false
    # logging:
    #   driver: "none"
    networks:
      brid2nginx:
      bridge2mongo:

#* NGINX
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      api1:
        condition: service_started
      api2:
        condition: service_started
      api3:
        condition: service_started
    attach: false
    logging:
      driver: "none"
    networks:
      brid2nginx:

networks:
  bridge2mongo:
    name: bridge2mongo
    driver: bridge
  brid2nginx:
    name: brid2nginx
    driver: bridge
